export { HeroSection } from "./hero"
export { AboutSection } from "./about"
export { SkillsSection } from "./skills"
export { ProjectsSection } from "./projects"
export { EducationSection } from "./education"
export { ContactSection } from "./contact"
